== Welcome to the lab environment!

Welcome to the lab environment! Here a few tips for completing these
challenges.

* This sidebar can be resized by clicking and dragging on the three
vertical dots. This helps to avoid horizontally scrolling code blocks.
* *Command blocks* show you the commands you need to run to complete the
challenge. These blocks will have a copy button in the top right corner.
* *Output blocks* show the expected output from the commands you run.
They look similar to command blocks, except they will *not* have a copy
button in the top right corner. Do *not* attempt to run the text from
these blocks as commands.

== Setting up the packaging workspace

Your first challenge is to set up your packaging workspace.

== Installing the necessary packages

Install the *rpmdevtools* package.

[source,bash,run]
----
sudo dnf -y install rpmdevtools
----

[source,nocopy]
----
### OUTPUT ABRIDGED ###
Installing:
 rpmdevtools                noarch   9.6-9.el10          rhel-10-for-x86_64-appstream-rpms    94 k
### OUTPUT ABRIDGED ###
----

== Defining the %packager macro

Define the *%packager* macro in the *~/.rpmmacros* file. This will be
used later when you generate *changelog* entries. You may use either
your actual name and email or the example ones provided below.

The command below uses shell output redirection to write the contents of
the *~/.rpmmacros* file. If you like, you can write the same content to
that file manually with a command-line text editor such as vim or nano.

[source,bash,run]
----
echo '%packager First Last <first@example.com>' >> ~/.rpmmacros
----

Use the *rpm* command to expand the macro to validate that it is defined
correctly.

[source,bash,run]
----
rpm --eval '%packager'
----

[source,nocopy]
----
First Last <first@example.com>
----

== Create the rpmbuild directory tree

Finally, run the *rpmdev-setuptree* command to create the default
directories for building packages.

[source,bash,run]
----
rpmdev-setuptree
----

You can observe the directories that were created using the *tree*
command.

[source,bash,run]
----
tree rpmbuild
----

[source,nocopy]
----
rpmbuild
├── BUILD
├── RPMS
├── SOURCES
├── SPECS
└── SRPMS

5 directories, 0 files
----

That concludes this challenge. In the next challenge, you will build
your first package using this environment and the tools that you
installed.
