== Packaging cello

Your next challenge is to package *cello*, a program written in C.
Because this program must be compiled from source, this spec file will
have some notable differences from the previous one.

=== Obtaining the source files

Navigate to the *rpmbuild* directory.

[source,bash,run]
----
cd /home/rhel/rpmbuild
----

The source code archive for *cello* is located at
*~/downloads/cello-1.0.tar.gz* on your system. There is also a patch
file located at *~/downloads/cello-output-first-patch.patch* that you
will include in the package. This patch will change the output of the
program from the default "`Hello World!`" to "`Hello World from my very
first patch!`". You will be able to observe this output after you build
and install the package. Move these source files into the *SOURCES*
directory.

[source,bash,run]
----
mv -v ~/downloads/cello-1.0.tar.gz ~/downloads/cello-output-first-patch.patch SOURCES/
----

[source,nocopy]
----
renamed '/home/rhel/downloads/cello-1.0.tar.gz' -> 'SOURCES/cello-1.0.tar.gz'
renamed '/home/rhel/downloads/cello-output-first-patch.patch' -> 'SOURCES/cello-output-first-patch.patch'
----

Verify the source code archive and patch file are in the correct
location.

[source,bash,run]
----
ls SOURCES/cello*
----

[source,nocopy]
----
SOURCES/cello-1.0.tar.gz  SOURCES/cello-output-first-patch.patch
----

=== Writing the spec file

Here is a table of some of the additional preamble tags you will use in
this spec file and their purpose.

[width="100%",cols="50%,50%",options="header",]
|===
|Tag |Use
|Patch |file name or URL of patch to apply to the source code

|BuildRequires |packages that must be installed prior to building this
package
|===

Define the *NVR* (*Name*, *Version*, *Release*) of the package. For now,
set the version to *0*, even though this does not match the version of
the software. You will set this to the correct version in a future step.

[source,bash,run]
----
cat >> SPECS/cello.spec << EOF
Name:           cello
Version:        0
Release:        1%{?dist}
EOF
----

Unlike the *bello* spec file, you will *not* define *BuildArch* as
*noarch*.  This is because this application is natively compiled for
specific architectures.  *BuildArch* will be automatically defined based
on the architecture of the machine you build the package on.

Define the *Summary*, *License*, and *URL* of the software.  Define
*Source* as the link where one may download the source code archive if
they did not have it, making sure the last segment matches our source
code archive filename.  Define *Patch* as the patch file name.  Add
build requirements for *gcc* and *make* since these will be needed to
build the software.

[source,bash,run]
----
cat >> SPECS/cello.spec << EOF
Summary:        Hello World example implemented in C
License:        GPL-3.0-or-later
URL:            https://github.com/redhat-developer/rpm-packaging-guide
Source:         %{url}/raw/master/example-code/cello-%{version}.tar.gz
Patch:          cello-output-first-patch.patch
BuildRequires:  gcc
BuildRequires:  make
EOF
----

The last part of the preamble is *%description*.

Add a sentence describing the software included in the package.

[source,bash,run]
----
cat >> SPECS/cello.spec << EOF

%description
The long description for our Hello World Example implemented in C.
EOF
----

This completes the preamble of the spec file.

The next part of the spec file is *%prep*. This is used to perform any
steps needed to prepare the source code for building the software.

Add the *%autosetup* macro, which will extract the source code archive
and apply the patch file defined in the preamble.

[source,bash,run]
----
cat >> SPECS/cello.spec << EOF

%prep
%autosetup
EOF
----

The next part of the spec file is *%build*. This is used to perform any
steps needed to build the software.

While *bello* in the previous challenge did not need to be compiled, the
same is not true for *cello*. Its source code must be compiled into an
executable binary. This is done with the *make* command, which uses
instructions from *cello*'s Makefile.

Add the *%make_build* macro, which will run the *make* command with
packaging-specific options.

[source,bash,run]
----
cat >> SPECS/cello.spec << EOF

%build
%make_build
EOF
----

The next part of the spec file is *%install*. This is used to perform
any steps needed to place files and directories into the appropriate
locations, relative to the *%\{buildroot}*.

Add the *%make_install* macro, which will run the *make install* command
with packaging-specific options. This will copy files into the
*%\{buildroot}*.

[source,bash,run]
----
cat >> SPECS/cello.spec << EOF

%install
%make_install
EOF
----

The next part of the spec file is *%files*. Here you will create a
manifest of what files are included in your package.

Add the *LICENSE* file with the *%license* attribute.

You will also list the rest of the files that are expected to be on the
target system, based on the contents of the *%\{buildroot}*. In this
case that is just the *cello* executable in */usr/bin*.

[source,bash,run]
----
cat >> SPECS/cello.spec << EOF

%files
%license LICENSE
%{_bindir}/cello
EOF
----

The last part of the spec file is *%changelog*. It lists the changes
that have happened to the package between different versions and
releases.

Leave this empty for now.

[source,bash,run]
----
cat >> SPECS/cello.spec << EOF

%changelog
EOF
----

Use the *rpmdev-bumpspec* tool to create a changelog entry. This tool
will also change the *Version* field in the preamble to the correct
value.

[source,bash,run]
----
rpmdev-bumpspec --new 1.0 --comment 'Initial package' SPECS/cello.spec
----

Review the spec file you have written.

[source,bash,run]
----
cat SPECS/cello.spec
----

[source,nocopy]
----
Name:           cello
Version:        1.0
Release:        1%{?dist}
Summary:        Hello World example implemented in C
License:        GPL-3.0-or-later
URL:            https://github.com/redhat-developer/rpm-packaging-guide
Source:         %{url}/raw/master/example-code/cello-%{version}.tar.gz
Patch:          cello-output-first-patch.patch
BuildRequires:  gcc
BuildRequires:  make

%description
The long description for our Hello World Example implemented in C.

%prep
%autosetup

%build
%make_build

%install
%make_install

%files
%license LICENSE
%{_bindir}/cello

%changelog
* Mon Mar 02 2026 First Last <first@example.com> - 1.0-1
- Initial package

----

=== Building the package

Because this package has build requirements defined in the preamble, you
must install them before building the package.

Install the build requirements with the *dnf builddep* command.

[source,bash,run]
----
sudo dnf -y builddep SPECS/cello.spec
----

[source,nocopy]
----
### OUTPUT ABRIDGED ###
Installing:
 gcc                  x86_64   14.3.1-2.1.el10           rhel-10-for-x86_64-appstream-rpms    38 M
 make                 x86_64   1:4.4.1-9.el10            rhel-10-for-x86_64-baseos-rpms      591 k
### OUTPUT ABRIDGED ###
----

Once the build requirements are installed, you can build the package
using the *rpmbuild* command. This will create a package and a source
package in the appropriate directories in your packaging workspace.
Because this package contains a compiled binary, special debug packages
(*cello-debuginfo* and *cello-debugsource*) will also be created. You
can ignore these during this lab.

[source,bash,run]
----
rpmbuild -ba SPECS/cello.spec
----

[source,nocopy]
----
### OUTPUT ABRIDGED ###
Wrote: /home/rhel/rpmbuild/SRPMS/cello-1.0-1.el10.src.rpm
Wrote: /home/rhel/rpmbuild/RPMS/x86_64/cello-debugsource-1.0-1.el10.x86_64.rpm
Wrote: /home/rhel/rpmbuild/RPMS/x86_64/cello-debuginfo-1.0-1.el10.x86_64.rpm
Wrote: /home/rhel/rpmbuild/RPMS/x86_64/cello-1.0-1.el10.x86_64.rpm
### OUTPUT ABRIDGED ###
----

Use the *rpm* command to list the contents of the source package. In
addition to the spec file and source code archive, the patch file is
also included.

[source,bash,run]
----
rpm --query --list --package SRPMS/cello-1.0-1.el10.src.rpm
----

[source,nocopy]
----
cello-1.0.tar.gz
cello-output-first-patch.patch
cello.spec
----

Use the *rpm* command to list the contents of the package. Because this
package contains a compiled binary, it will include some additional
files and directories under */usr/lib/.build-id* that were added
automatically.

[source,bash,run]
----
rpm --query --list --package RPMS/x86_64/cello-1.0-1.el10.x86_64.rpm
----

[source,nocopy]
----
/usr/bin/cello
/usr/lib/.build-id
/usr/lib/.build-id/07
/usr/lib/.build-id/07/9798846dd560306a06826894e645b09221b0f6
/usr/share/licenses/cello
/usr/share/licenses/cello/LICENSE
----

Now that your package is built, you can install it on the system.

[source,bash,run]
----
sudo dnf -y install RPMS/x86_64/cello-1.0-1.el10.x86_64.rpm
----

[source,nocopy]
----
### OUTPUT ABRIDGED ###
Installing:
 cello              x86_64              1.0-1.el10                 @commandline               11 k
### OUTPUT ABRIDGED ###
----

Finally, run the *cello* program. Notice how the output includes the
modified message from our patch file. If you built this package again
without the patch file, the output would be "`Hello World!`" instead.

[source,bash,run]
----
cello
----

[source,nocopy]
----
Hello World from my very first patch!
----

That concludes this challenge. In the next challenge, you will be
packaging a Python program named *pello*.
