== Packaging pello

Your next challenge is to package *pello*, a program written in Python.
This will be an architecture-independent (*noarch*) package like
*bello*, but it will also have files that need to be compiled to byte
code.

=== Obtaining the source files

Navigate to the *rpmbuild* directory.

[source,bash,run]
----
cd /home/rhel/rpmbuild
----

The source code archive for pello is located at
*~/downloads/Pello-1.0.4.tar.gz* on your system. Move the source code
archive into the *SOURCES* directory.

[source,bash,run]
----
mv -v ~/downloads/Pello-1.0.4.tar.gz SOURCES/
----

[source,nocopy]
----
renamed '/home/rhel/downloads/Pello-1.0.4.tar.gz' -> 'SOURCES/Pello-1.0.4.tar.gz'
----

Verify the source code archive is in the correct location.

[source,bash,run]
----
ls SOURCES/Pello*
----

[source,nocopy]
----
SOURCES/Pello-1.0.4.tar.gz
----

=== Writing the spec file

Define the *NVR* (*Name*, *Version*, *Release*) of the package. For now,
set the version to *0*, even though this does not match the version of
the software. You will set this to the correct version in a future step.

[source,bash,run]
----
cat >> SPECS/pello.spec << EOF
Name:           pello
Version:        0
Release:        1%{?dist}
EOF
----

Define *BuildArch* as *noarch* to mark the package as architecture
independent.  Define the *Summary*, *License*, and *URL* for the
software.  *Pello* is available from the PyPI website, so instead of
defining *Source* directly you can use the *%pypi_source* macro to
generate the link.  The last portion of this link (the file name) will
match the source code archive located in *SOURCES*.

Add build requirements for the packages needed to build the software:
*python3-devel*, *pyproject-rpm-macros*, *python3-wheel*, *python3-pip*,
and *python3-setuptools*.  Also add a build requirement for
*python3-pytest*, which will be used to run the upstream unit tests.

[source,bash,run]
----
cat >> SPECS/pello.spec << EOF
BuildArch:      noarch
Summary:        An example Python Hello World package
License:        MIT-0
URL:            https://github.com/fedora-python/Pello
Source:         %{pypi_source Pello}
BuildRequires:  python3-devel
BuildRequires:  pyproject-rpm-macros
BuildRequires:  python3-wheel
BuildRequires:  python3-pip
BuildRequires:  python3-setuptools
BuildRequires:  python3-pytest
EOF
----

The last part of the preamble is *%description*.

Add a few sentences describing the software included in the package.

[source,bash,run]
----
cat >> SPECS/pello.spec << EOF

%description
Pello is an example package that will be used as a part of Fedora Python
Packaging Guidelines.  The only thing that this package does is printing
Hello World! on the command line.
EOF
----

This completes the preamble of the spec file.

The next part of the spec file is *%prep*. This is used to perform any
steps needed to prepare the source code for building the software.

Add the *%autosetup* macro, which will extract the source code archive.
Note that you will need to use the *-n* flag to indicate that the top
level directory of the source code archive doesn't match the default
*%\{name}-%\{version}* due to the capital P.

[source,bash,run]
----
cat >> SPECS/pello.spec << EOF

%prep
%autosetup -n Pello-%{version}
EOF
----

The next part of the spec file is *%build*. This is used to perform any
steps needed to build the software.

*Pello* is an architecture-independent program, but it does need to be
compiled to byte code.

Add the *%pyproject_wheel* macro, which will build a Python wheel with
packaging-specific options.

[source,bash,run]
----
cat >> SPECS/pello.spec << EOF

%build
%pyproject_wheel
EOF
----

The next part of the spec file is *%install*. This is used to perform
any steps needed to place files and directories into the appropriate
locations, relative to the *%\{buildroot}*.

Add the *%pyproject_install* macro, which will use the Python wheel to
install files into the *%\{buildroot}*.

[source,bash,run]
----
cat >> SPECS/pello.spec << EOF

%install
%pyproject_install
EOF
----

The next part of the spec file is *%check*. This is used to perform any
steps needed to validate the software functions correctly, such as
running the upstream unit tests.

Add the *%pytest* macro, which will run the *pytest* command with
packaging-specific options.

[source,bash,run]
----
cat >> SPECS/pello.spec << EOF

%check
%pytest
EOF
----

The next part of the spec file is *%files*. Here you will create a
manifest of what files are included in your package.

Add the *LICENSE.txt* file with the *%license* attribute. Similar to the
*%license* attribute, there is also a *%doc* attribute to mark files as
documentation in the package metadata. The notable difference between
these attributes is that *dnf* can be configured to skip documentation
files, but license files are always included.  Add the *README.md*
file with the *%doc* attribute.

You will also list the rest of the files that are expected to be on the
target system, based on the contents of the *%\{buildroot}*. In addition
to the *pello_greeting* file in */usr/bin*, you also need to list the
files in the *%\{python3_sitelib}*, which expands to
*/usr/lib/python3.12/site-packages*.

[source,bash,run]
----
cat >> SPECS/pello.spec << EOF

%files
%license LICENSE.txt
%doc README.md
%{_bindir}/pello_greeting
%{python3_sitelib}/pello
%{python3_sitelib}/Pello-%{version}.dist-info
EOF
----

The last part of the spec file is *%changelog*. It lists the changes
that have happened to the package between different versions and
releases.

Leave this empty for now.

[source,bash,run]
----
cat >> SPECS/pello.spec << EOF

%changelog
EOF
----

Use the *rpmdev-bumpspec* tool to create a changelog entry. This tool
will also change the *Version* field in the preamble to the correct
value.

[source,bash,run]
----
rpmdev-bumpspec --new 1.0.4 --comment 'Initial package' SPECS/pello.spec
----

Review the spec file you have written.

[source,bash,run]
----
cat SPECS/pello.spec
----

[source,nocopy]
----
Name:           pello
Version:        1.0.4
Release:        1%{?dist}
BuildArch:      noarch
Summary:        An example Python Hello World package
License:        MIT-0
URL:            https://github.com/fedora-python/Pello
Source:         %{pypi_source Pello}
BuildRequires:  python3-devel
BuildRequires:  pyproject-rpm-macros
BuildRequires:  python3-wheel
BuildRequires:  python3-pip
BuildRequires:  python3-setuptools
BuildRequires:  python3-pytest

%description
Pello is an example package that will be used as a part of Fedora Python
Packaging Guidelines.  The only thing that this package does is printing
Hello World! on the command line.

%prep
%autosetup -n Pello-%{version}

%build
%pyproject_wheel

%install
%pyproject_install

%check
%pytest

%files
%license LICENSE.txt
%doc README.md
%{_bindir}/pello_greeting
%{python3_sitelib}/pello
%{python3_sitelib}/Pello-%{version}.dist-info

%changelog
* Mon Mar 02 2026 First Last <first@example.com> - 1.0.4-1
- Initial package

----

=== Building the package

NOTE: Some of the build requirements are in the CodeReady Builder
repository.  On RHEL this repository is available by default, but not
enabled by default.  In this lab environment it has already been enabled
for you.

Install the build requirements with the *dnf builddep* command.

[source,bash,run]
----
sudo dnf -y builddep SPECS/pello.spec
----

[source,nocopy]
----
### OUTPUT ABRIDGED ###
Installing:
 pyproject-rpm-macros   noarch 1.16.2-1.el10       codeready-builder-for-rhel-10-x86_64-rpms  48 k
 python3-devel          x86_64 3.12.12-3.el10_1    rhel-10-for-x86_64-appstream-rpms         336 k
 python3-pip            noarch 23.3.2-7.el10       rhel-10-for-x86_64-appstream-rpms         3.2 M
 python3-pytest         noarch 7.4.3-5.el10        codeready-builder-for-rhel-10-x86_64-rpms 760 k
 python3-setuptools     noarch 69.0.3-12.el10_0    rhel-10-for-x86_64-baseos-rpms            1.6 M
 python3-wheel          noarch 1:0.41.2-5.el10_1.1 codeready-builder-for-rhel-10-x86_64-rpms 173 k
### OUTPUT ABRIDGED ###
----

Once the build requirements are installed, you can build the package
using the *rpmbuild* command. This will create a package and a source
package in the appropriate directories in your packaging workspace.

[source,bash,run]
----
rpmbuild -ba SPECS/pello.spec
----

[source,nocopy]
----
### OUTPUT ABRIDGED ###
Wrote: /home/rhel/rpmbuild/SRPMS/pello-1.0.4-1.el10.src.rpm
Wrote: /home/rhel/rpmbuild/RPMS/noarch/pello-1.0.4-1.el10.noarch.rpm
### OUTPUT ABRIDGED ###
----

Use the *rpm* command to list the contents of the source package.

[source,bash,run]
----
rpm --query --list --package SRPMS/pello-1.0.4-1.el10.src.rpm
----

[source,nocopy]
----
Pello-1.0.4.tar.gz
pello.spec
----

Use the *rpm* command to list the contents of the package.

[source,bash,run]
----
rpm --query --list --package RPMS/noarch/pello-1.0.4-1.el10.noarch.rpm
----

[source,nocopy]
----
/usr/bin/pello_greeting
/usr/lib/python3.12/site-packages/Pello-1.0.4.dist-info
/usr/lib/python3.12/site-packages/Pello-1.0.4.dist-info/INSTALLER
/usr/lib/python3.12/site-packages/Pello-1.0.4.dist-info/LICENSE.txt
/usr/lib/python3.12/site-packages/Pello-1.0.4.dist-info/METADATA
/usr/lib/python3.12/site-packages/Pello-1.0.4.dist-info/WHEEL
/usr/lib/python3.12/site-packages/Pello-1.0.4.dist-info/entry_points.txt
/usr/lib/python3.12/site-packages/Pello-1.0.4.dist-info/top_level.txt
/usr/lib/python3.12/site-packages/pello
/usr/lib/python3.12/site-packages/pello/__init__.py
/usr/lib/python3.12/site-packages/pello/__main__.py
/usr/lib/python3.12/site-packages/pello/__pycache__
/usr/lib/python3.12/site-packages/pello/__pycache__/__init__.cpython-312.opt-1.pyc
/usr/lib/python3.12/site-packages/pello/__pycache__/__init__.cpython-312.pyc
/usr/lib/python3.12/site-packages/pello/__pycache__/__main__.cpython-312.opt-1.pyc
/usr/lib/python3.12/site-packages/pello/__pycache__/__main__.cpython-312.pyc
/usr/lib/python3.12/site-packages/pello/__pycache__/pello_greeting.cpython-312.opt-1.pyc
/usr/lib/python3.12/site-packages/pello/__pycache__/pello_greeting.cpython-312.pyc
/usr/lib/python3.12/site-packages/pello/pello_greeting.py
/usr/share/doc/pello
/usr/share/doc/pello/README.md
/usr/share/licenses/pello
/usr/share/licenses/pello/LICENSE.txt
----

Now that your package is built, you can install it on the system.

[source,bash,run]
----
sudo dnf -y install RPMS/noarch/pello-1.0.4-1.el10.noarch.rpm
----

[source,nocopy]
----
### OUTPUT ABRIDGED ###
Installing:
 pello              noarch              1.0.4-1.el10               @commandline               13 k
### OUTPUT ABRIDGED ###
----

Finally, run the *pello_greeting* program.

[source,bash,run]
----
pello_greeting
----

[source,nocopy]
----
Hello World!
----

That concludes this challenge. In the next challenge, you will build
*pello* with *mock* instead of *rpmbuild*.
