== Building with mock

Your final challenge is to build the *pello* package with *mock* instead
of *rpmbuild*. This will allow you to build a package that is compatible
with RHEL 9, even though the build host is RHEL 10.

This challenge uses files that you created during the *pello* challenge,
so if you skipped it you need to go back and complete it by clicking the
"Previous" button.

Expand the section headers below to work on each section of this
challenge.

== Install and configure mock

[%collapsible]
====

NOTE: Mock is not part of RHEL.  It is available from the EPEL (Extra
Packages for Enterprise Linux) repository.  This is a third-party
repository that is not available by default in RHEL.  In this lab
environment it has already been enabled for you.

Install the *mock* package from the EPEL repository.

[source,bash,run]
----
sudo dnf -y install mock
----

[source,nocopy]
----
### OUTPUT ABRIDGED ###
Installing:
 mock                         noarch 6.6-1.el10_1          epel                              299 k
### OUTPUT ABRIDGED ###
----

In order to use *mock*, a user must be a member of the *mock* group.

Use the *gpasswd* command to add the *rhel* user to the *mock* group.

[source,bash,run]
----
sudo gpasswd --add rhel mock
----

[source,nocopy]
----
Adding user root to group mock
----

You can use the *groups* command to verify the group membership.

[source,bash,run]
----
groups rhel
----

[source,nocopy]
----
rhel : rhel wheel mock
----

Start a new login shell to have the new group membership take effect.

[source,bash,run]
----
sudo -iu rhel
----

Expand the next section header to continue the challenge.

====

== Build with mock from a source package

[%collapsible]
====

Navigate to the *rpmbuild* directory.

[source,bash,run]
----
cd /home/rhel/rpmbuild
----

Use the *mock* command to build *pello* for RHEL 9 from the previously
built source package. This will take a bit longer to run than the
*rpmbuild* command, because it must create the chroot environment.

[source,bash,run]
----
mock --root rhel-9-x86_64 SRPMS/pello-1.0.4-1.el10.src.rpm
----

[source,nocopy]
----
### OUTPUT ABRIDGED ###
Wrote: /builddir/build/RPMS/pello-1.0.4-1.el9.noarch.rpm
Finish: rpmbuild pello-1.0.4-1.el10.src.rpm
Finish: build phase for pello-1.0.4-1.el10.src.rpm
INFO: Done(SRPMS/pello-1.0.4-1.el10.src.rpm) Config(rhel-9-x86_64) 1 minutes 12 seconds
INFO: Results and/or logs in: /var/lib/mock/rhel-9-x86_64/result
Finish: run
----

The output from the last command shows the resulting packages are
located in the */var/lib/mock/rhel-9-x86_64/result* directory.

Use the *rpm* command to show the dependency on *python(abi)* in this
package. The version of this dependency corresponds to the default
Python version (3.9) in RHEL 9.

[source,bash,run]
----
rpm --query --requires --package /var/lib/mock/rhel-9-x86_64/result/pello-1.0.4-1.el9.noarch.rpm | grep 'python(abi)'
----

[source,nocopy]
----
python(abi) = 3.9
----

Now do the same for the package you built earlier with *rpmbuild*. The
version of this dependency corresponds to the default Python version
(3.12) in RHEL 10.

[source,bash,run]
----
rpm --query --requires --package RPMS/noarch/pello-1.0.4-1.el10.noarch.rpm | grep 'python(abi)'
----

[source,nocopy]
----
python(abi) = 3.12
----

Expand the next section header to continue the challenge.

====

== Build with mock from a spec file

[%collapsible]
====

In addition to rebuilding source packages, *mock* is also able to build
directly from a spec file and the corresponding sources. Before you do
this, increment the *Release* in the *pello* spec file using
*rpmdev-bumpspec*, which will also add the appropriate changelog entry.

[source,bash,run]
----
rpmdev-bumpspec --comment 'Rebuild' SPECS/pello.spec
----

Use *mock* to build *pello* for RHEL 9 from the *pello* spec file and
the *SOURCES* directory. This will be a bit faster than the first time
you ran *mock* thanks to the chroot being cached, although still not
quite as fast as running *rpmbuild* directly.

[source,bash,run]
----
mock --root rhel-9-x86_64 --spec SPECS/pello.spec --sources SOURCES
----

[source,nocopy]
----
### OUTPUT ABRIDGED ###
Wrote: /builddir/build/RPMS/pello-1.0.4-2.el9.noarch.rpm
Finish: rpmbuild pello-1.0.4-2.el9.src.rpm
Finish: build phase for pello-1.0.4-2.el9.src.rpm
INFO: Done(/var/lib/mock/rhel-9-x86_64/result/pello-1.0.4-2.el9.src.rpm) Config(rhel-9-x86_64) 0 minutes 13 seconds
INFO: Results and/or logs in: /var/lib/mock/rhel-9-x86_64/result
Finish: run
----

Use *rpm* to inspect the resulting package.

[source,bash,run]
----
rpm --query --info --package /var/lib/mock/rhel-9-x86_64/result/pello-1.0.4-2.el9.noarch.rpm
----

[source,nocopy]
----
Name        : pello
Version     : 1.0.4
Release     : 2.el9
Architecture: noarch
Install Date: (not installed)
Group       : Unspecified
Size        : 8035
License     : MIT-0
Signature   : (none)
Source RPM  : pello-1.0.4-2.el9.src.rpm
Build Date  : Mon 02 Mar 2026 03:50:08 PM UTC
Build Host  : rhel
URL         : https://github.com/fedora-python/Pello
Summary     : An example Python Hello World package
Description :
Pello is an example package that will be used as a part of Fedora Python
Packaging Guidelines.  The only thing that this package does is printing
Hello World! on the command line.
----

That concludes this challenge, which is the final challenge for this
track.

====
